// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvq7EwQamfEnNKWWsz0SWV2tWyukp2sQA',
    appId: '1:1073529171853:web:a68773dc7cb089f11a57c4',
    messagingSenderId: '1073529171853',
    projectId: 'travelbuddy-98eac',
    authDomain: 'travelbuddy-98eac.firebaseapp.com',
    storageBucket: 'travelbuddy-98eac.appspot.com',
    measurementId: 'G-WWDMFMWHFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb3StwDbE9IRO1_LkteNICMqajiO4hiXQ',
    appId: '1:1073529171853:android:a9a3895526257daf1a57c4',
    messagingSenderId: '1073529171853',
    projectId: 'travelbuddy-98eac',
    storageBucket: 'travelbuddy-98eac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaIN8A-YQPRqDLF3sKkw1pVMkmMdYodpE',
    appId: '1:1073529171853:ios:5ddffe7c6944db011a57c4',
    messagingSenderId: '1073529171853',
    projectId: 'travelbuddy-98eac',
    storageBucket: 'travelbuddy-98eac.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );
}
